/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack.view;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList; 
import java.util.List; 
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton; 
import javax.swing.JComboBox; 
import javax.swing.JOptionPane;
import javax.swing.JTable; 
import javax.swing.JTextField; 
import javax.swing.table.DefaultTableModel;
import pack.control.c_koneksi; 
import pack.control.controllerToko; 
import pack.model.m_toko; 
import pack.view.login;
/**
 *
 * @author Smktelkom
 */
public class home extends javax.swing.JFrame {
    controllerToko ctoko;
    List<m_toko>listdata = new ArrayList<>();
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        ctoko = new controllerToko (this);
        ctoko.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        tfKode = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        cbmakan = new javax.swing.JComboBox<>();
        cbKategori = new javax.swing.JComboBox<>();
        bEdit = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        bDel = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        bSearch = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbPack = new javax.swing.JComboBox<>();
        bExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        admin.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        getContentPane().add(admin);
        admin.setBounds(560, 30, 90, 30);

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jLabel2.setText("Nama Barang");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 130, 120, 30);

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel1.setText("Data Barang di Toko");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 20, 200, 40);

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jLabel3.setText("Admin Toko :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(470, 30, 80, 30);

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jLabel4.setText("Kode Barang");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 90, 120, 30);

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jLabel5.setText("Pencarian Berdasarkan Kategori Makanan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 290, 250, 30);

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jLabel6.setText("Kategori Barang");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 170, 120, 30);

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jLabel7.setText("Jenis Packaging");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 210, 120, 30);
        getContentPane().add(tfHarga);
        tfHarga.setBounds(180, 250, 300, 30);
        getContentPane().add(tfKode);
        tfKode.setBounds(180, 90, 300, 30);
        getContentPane().add(tfNama);
        tfNama.setBounds(180, 130, 300, 30);

        cbmakan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Barang Lain" }));
        getContentPane().add(cbmakan);
        cbmakan.setBounds(310, 290, 170, 30);

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Barang Lain" }));
        getContentPane().add(cbKategori);
        cbKategori.setBounds(180, 170, 300, 30);

        bEdit.setText("Ubah");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        getContentPane().add(bEdit);
        bEdit.setBounds(520, 130, 110, 30);

        bSave.setText("Simpan");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        getContentPane().add(bSave);
        bSave.setBounds(520, 90, 110, 30);

        bDel.setText("Hapus");
        bDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelActionPerformed(evt);
            }
        });
        getContentPane().add(bDel);
        bDel.setBounds(520, 210, 110, 30);

        bClear.setText("Bersihkan");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });
        getContentPane().add(bClear);
        bClear.setBounds(520, 170, 110, 30);

        bSearch.setText("Cari");
        bSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearchActionPerformed(evt);
            }
        });
        getContentPane().add(bSearch);
        bSearch.setBounds(520, 290, 110, 30);

        jLabel8.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        jLabel8.setText("Harga Barang");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 250, 120, 30);

        cbPack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pack" }));
        getContentPane().add(cbPack);
        cbPack.setBounds(180, 210, 300, 30);

        bExit.setText("Keluar");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        getContentPane().add(bExit);
        bExit.setBounds(520, 250, 110, 30);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Kategori", "Packaging", "Harga"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 350, 580, 140);

        setBounds(0, 0, 689, 602);
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        ctoko.SimpanData();
        ctoko.isiTable();
    }//GEN-LAST:event_bSaveActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        ctoko.Ubah();
        ctoko.isiTable();
    }//GEN-LAST:event_bEditActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        ctoko.Reset();
    }//GEN-LAST:event_bClearActionPerformed

    private void bDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelActionPerformed
        ctoko.Hapus();
        ctoko.isiTable();
    }//GEN-LAST:event_bDelActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        dispose();
    }//GEN-LAST:event_bExitActionPerformed

    private void bSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchActionPerformed
        ctoko.CariKategori();
    }//GEN-LAST:event_bSearchActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        int baris = table1.getSelectedRow();
        if (baris != -1) {
            tfKode.setText(table1.getValueAt(baris, 0).toString());
            tfNama.setText((String) table1.getValueAt(baris, 1).toString());
            cbKategori.setSelectedItem(table1.getValueAt(baris, 2).toString());
            cbPack.setSelectedItem(table1.getValueAt(baris, 3).toString());
            tfHarga.setText(table1.getValueAt(baris, 4).toString());
        }
    }//GEN-LAST:event_table1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String user = login.user;
        admin.setText(""+user);
    }//GEN-LAST:event_formWindowOpened
    
    public JTextField getTxtKode(){ 
        return tfKode; 
    } 
    public JTextField getTxtNama(){ 
        return tfNama; 
    } 
    public JTextField getTxtHarga(){ 
        return tfHarga; 
    } 
    public JComboBox getCbKategori(){ 
        return cbKategori; 
    } 
    public JComboBox getCbJenis(){ 
        return cbPack; 
    } 
    public JComboBox getCbCariKategori(){ 
        return cbmakan; 
    } 
    public JButton getButtonHapus(){ 
        return bDel; 
    } 
     
    public JButton getButtonBersih(){ 
        return bClear; 
    } 
    public JButton getButtonSimpan(){ 
        return bSave; 
    } 
    public JButton getButtonUbah(){ 
        return bEdit; 
    } 
    public JButton getButtonKeluar(){ 
        return bExit; 
    } 
    public JTable getTableData(){ 
        return table1; 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bDel;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bSave;
    private javax.swing.JButton bSearch;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JComboBox<String> cbPack;
    private javax.swing.JComboBox<String> cbmakan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table1;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfKode;
    private javax.swing.JTextField tfNama;
    // End of variables declaration//GEN-END:variables
}
